// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */

import { initFormatters } from './formatters'
import type { Locales, Translations } from './i18n-types'
import { loadedFormatters, loadedLocales, locales } from './i18n-util'

import en from './en'
import fr from './fr'

import en_My_Awesome_Plugin from './en/My Awesome Plugin'
import fr_My_Awesome_Plugin from './fr/My Awesome Plugin'

const localeTranslations = {
	en: {
		...en,
		'My Awesome Plugin': en_My_Awesome_Plugin
	},
	fr: {
		...fr,
		'My Awesome Plugin': fr_My_Awesome_Plugin
	},
}

export const loadLocale = (locale: Locales): void => {
	if (loadedLocales[locale]) return

	loadedLocales[locale] = localeTranslations[locale] as unknown as Translations
	loadFormatters(locale)
}

export const loadAllLocales = (): void => locales.forEach(loadLocale)

export const loadFormatters = (locale: Locales): void => {
	loadedFormatters[locale] = initFormatters(locale)
}
