// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'en'
	| 'fr'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	GUARDS: {
		/**
		 * This command is currently desactivated.
		 */
		DISABLED_COMMAND: string
		/**
		 * This bot is currently in maintenance mode.
		 */
		MAINTENANCE: string
		/**
		 * This command can only be used in a server.
		 */
		GUILD_ONLY: string
		/**
		 * This command can only be used in a NSFW channel.
		 */
		NSFW: string
	}
	ERRORS: {
		/**
		 * An unknown error occured.
		 */
		UNKNOWN: string
	}
	COMMANDS: {
		INVITE: {
			/**
			 * Invite me to your server!
			 */
			TITLE: string
			/**
			 * [Click here]({link}) to invite me!
			 * @param {string} link
			 */
			DESCRIPTION: RequiredParams<'link'>
		}
		PREFIX: {
			/**
			 * Prefix changed to `{prefix}`.
			 * @param {string} prefix
			 */
			CHANGED: RequiredParams<'prefix'>
		}
		MAINTENANCE: {
			/**
			 * Maintenance mode set to `{state}`.
			 * @param {string} state
			 */
			SUCCESS: RequiredParams<'state'>
		}
		STATS: {
			HEADERS: {
				/**
				 * Commands
				 */
				COMMANDS: string
				/**
				 * Guild
				 */
				GUILDS: string
				/**
				 * Active Users
				 */
				ACTIVE_USERS: string
				/**
				 * Users
				 */
				USERS: string
			}
		}
		HELP: {
			/**
			 * Help pannel
			 */
			TITLE: string
			/**
			 * {category} Commands
			 * @param {string} category
			 */
			CATEGORY_TITLE: RequiredParams<'category'>
			SELECT_MENU: {
				/**
				 * Select a category
				 */
				TITLE: string
				/**
				 * {category} commands
				 * @param {string} category
				 */
				CATEGORY_DESCRIPTION: RequiredParams<'category'>
			}
		}
	}
}

export type TranslationFunctions = {
	GUARDS: {
		/**
		 * This command is currently desactivated.
		 */
		DISABLED_COMMAND: () => LocalizedString
		/**
		 * This bot is currently in maintenance mode.
		 */
		MAINTENANCE: () => LocalizedString
		/**
		 * This command can only be used in a server.
		 */
		GUILD_ONLY: () => LocalizedString
		/**
		 * This command can only be used in a NSFW channel.
		 */
		NSFW: () => LocalizedString
	}
	ERRORS: {
		/**
		 * An unknown error occured.
		 */
		UNKNOWN: () => LocalizedString
	}
	COMMANDS: {
		INVITE: {
			/**
			 * Invite me to your server!
			 */
			TITLE: () => LocalizedString
			/**
			 * [Click here]({link}) to invite me!
			 */
			DESCRIPTION: (arg: { link: string }) => LocalizedString
		}
		PREFIX: {
			/**
			 * Prefix changed to `{prefix}`.
			 */
			CHANGED: (arg: { prefix: string }) => LocalizedString
		}
		MAINTENANCE: {
			/**
			 * Maintenance mode set to `{state}`.
			 */
			SUCCESS: (arg: { state: string }) => LocalizedString
		}
		STATS: {
			HEADERS: {
				/**
				 * Commands
				 */
				COMMANDS: () => LocalizedString
				/**
				 * Guild
				 */
				GUILDS: () => LocalizedString
				/**
				 * Active Users
				 */
				ACTIVE_USERS: () => LocalizedString
				/**
				 * Users
				 */
				USERS: () => LocalizedString
			}
		}
		HELP: {
			/**
			 * Help pannel
			 */
			TITLE: () => LocalizedString
			/**
			 * {category} Commands
			 */
			CATEGORY_TITLE: (arg: { category: string }) => LocalizedString
			SELECT_MENU: {
				/**
				 * Select a category
				 */
				TITLE: () => LocalizedString
				/**
				 * {category} commands
				 */
				CATEGORY_DESCRIPTION: (arg: { category: string }) => LocalizedString
			}
		}
	}
}

export type Formatters = {}
